In [1]:
v = list(range(1, 6))
v
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [2]:
v
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
x = [60, 70, 80, 90]
print(len(x))
print(x[0])
print(x[1])
print(x[-1])

4
60
70
90


In [5]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c
print(a)
print(b)
print(c)

[1 2 3]
[4 5 6]
[ 4 10 18]


In [6]:
import numpy as np
a = np.zeros((2,2))
print(a) 

b = np.ones((1,2))
print(b) 

c = np.full((2,2), 7)
print(c) 

d = np.eye(2)
print(d)

e = np.random.random((2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[0.09558893 0.0487614 ]
